# Generated by Django 5.2.6 on 2025-10-08 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=100)),
                ("address", models.TextField(default="", max_length=1000)),
                ("phone", models.CharField(max_length=14, verbose_name="Mobile")),
                ("email", models.EmailField(max_length=254)),
                ("loyalty_points", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        default="media/default_user.png",
                        upload_to="customer_pics",
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "delivery_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer's selected delivery region for fee calculation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.deliverylocation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(max_length=50, verbose_name="Employee ID")),
                ("name", models.CharField(default="", max_length=100)),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("MD", "Managing Director"),
                            ("AD", "Administrator"),
                            ("MG", "Manager"),
                            ("AC", "Accountant"),
                            ("CS", "Customer Service"),
                            ("DL", "Delivery Personnel"),
                            ("KS", "Kitchen Staff"),
                        ],
                        max_length=50,
                    ),
                ),
                ("phone", models.CharField(max_length=14, verbose_name="Mobile")),
                ("email", models.EmailField(max_length=254)),
                (
                    "image",
                    models.ImageField(
                        default="media/default_user.png",
                        upload_to="customer_pics",
                        verbose_name="Profile Picture",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
