# Generated by Django 5.2.6 on 2025-10-08 17:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CK", "Cakes"),
                            ("PS", "Pastry"),
                            ("JS", "Juices"),
                            ("DR", "Drinks"),
                            ("FD", "Foods"),
                            ("PR", "Proteins"),
                            ("SS", "Small Chops & Snacks Packs"),
                            ("ML", "Meals & Proteins"),
                            ("DT", "Desserts & Treats Packs"),
                            ("PC", "Pre-Order Cakes"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(max_length=500)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_non_veg", models.BooleanField(default=False)),
                ("stock", models.IntegerField(default=10)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=5, max_digits=2),
                ),
                (
                    "image",
                    models.ImageField(
                        default="media/default_item.png",
                        upload_to="item_pics",
                        verbose_name="Feature Image",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="combos_images/"
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.IntegerField(default=0)),
                (
                    "item1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combo_item1",
                        to="items.item",
                    ),
                ),
                (
                    "item2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combo_item2",
                        to="items.item",
                    ),
                ),
                (
                    "item3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combo_item3",
                        to="items.item",
                    ),
                ),
                (
                    "item4",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combo_item4",
                        to="items.item",
                    ),
                ),
                (
                    "item5",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combo_item5",
                        to="items.item",
                    ),
                ),
            ],
        ),
    ]
