# Generated by Django 5.2.6 on 2025-10-16 13:31

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=80,
                scale=None,
                size=[150, 150],
                upload_to="item_thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                null=True,
                quality=85,
                scale=None,
                size=[800, 800],
                upload_to="item_images/",
            ),
        ),
    ]
