# Generated by Django 5.2.6 on 2025-10-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeliveryLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Campus, College, Off Campus - Tipper Garage (Bus Stop only)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Delivery fee in Naira (₦)",
                        max_digits=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Delivery Region & Fee",
                "verbose_name_plural": "Delivery Regions & Fees",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_placed", models.DateField(blank=True, null=True)),
                ("time_placed", models.TimeField(blank=True, null=True)),
                ("expected_delivery_time", models.TimeField(blank=True, null=True)),
                ("delivered", models.BooleanField(default=False)),
                ("finalized", models.BooleanField(default=False)),
                ("used_loyalty_points", models.BooleanField(default=False)),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("hidden_from_customer", models.BooleanField(default=False)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=300, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("rating", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="OperatingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "closed_date",
                    models.DateField(
                        blank=True,
                        help_text="Set a specific date to close (e.g., Public Holiday).",
                        null=True,
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True,
                        help_text="Check to allow ordering on this day/date.",
                    ),
                ),
                (
                    "opening_time",
                    models.TimeField(
                        blank=True, help_text="The time ordering opens.", null=True
                    ),
                ),
                (
                    "closing_time",
                    models.TimeField(
                        blank=True, help_text="The time ordering closes.", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Operating Hour",
                "verbose_name_plural": "Operating Hours",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("closed_date__isnull", True)),
                        fields=("day",),
                        name="unique_day_hours",
                    )
                ],
            },
        ),
    ]
